version: "3.8"
services:
  dev-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest_learn
    ports:
      - 5432:5432
    networks:
      - nestlearn
networks:
  nestlearn:
